// AUTO-GENERATED by _build_continents.mjs — do not edit by hand.
// Country-level face-flag views for the 5 non-Europe continents (demo vote data).
import type { DesignOption } from '@/components/VotingDesignMap';

export type ContinentView = { key: string; title: string; isos: string[]; options: DesignOption[] };

export const CONTINENT_VIEWS: ContinentView[] = [
  {
    "key": "africa",
    "title": "Afrika",
    "isos": [
      "710",
      "504",
      "818",
      "834",
      "404",
      "516",
      "788",
      "231",
      "566",
      "288",
      "686",
      "012",
      "024",
      "204",
      "072",
      "854",
      "108",
      "120",
      "140",
      "148",
      "178",
      "180",
      "262",
      "226",
      "232",
      "748",
      "266",
      "270",
      "324",
      "624",
      "384",
      "426",
      "430",
      "434",
      "450",
      "454",
      "466",
      "478",
      "508",
      "562",
      "646",
      "694",
      "706",
      "728",
      "729",
      "768",
      "800",
      "894",
      "716"
    ],
    "options": [
      {
        "label": "Südafrika",
        "code": "710",
        "votes": 9490
      },
      {
        "label": "Marokko",
        "code": "504",
        "votes": 9402
      },
      {
        "label": "Ägypten",
        "code": "818",
        "votes": 9155
      },
      {
        "label": "Tansania",
        "code": "834",
        "votes": 9030
      },
      {
        "label": "Kenia",
        "code": "404",
        "votes": 8843
      },
      {
        "label": "Namibia",
        "code": "516",
        "votes": 8680
      },
      {
        "label": "Tunesien",
        "code": "788",
        "votes": 8526
      },
      {
        "label": "Äthiopien",
        "code": "231",
        "votes": 8314
      },
      {
        "label": "Nigeria",
        "code": "566",
        "votes": 8159
      },
      {
        "label": "Ghana",
        "code": "288",
        "votes": 8008
      },
      {
        "label": "Senegal",
        "code": "686",
        "votes": 7877
      },
      {
        "label": "Algerien",
        "code": "012",
        "votes": 7693
      },
      {
        "label": "Angola",
        "code": "024",
        "votes": 7466
      },
      {
        "label": "Benin",
        "code": "204",
        "votes": 7369
      },
      {
        "label": "Botswana",
        "code": "072",
        "votes": 7183
      },
      {
        "label": "Burkina Faso",
        "code": "854",
        "votes": 6979
      },
      {
        "label": "Burundi",
        "code": "108",
        "votes": 6853
      },
      {
        "label": "Kamerun",
        "code": "120",
        "votes": 6639
      },
      {
        "label": "Kap Verde",
        "code": "132",
        "votes": 6487,
        "lat": 16,
        "lng": -24
      },
      {
        "label": "Zentralafr. Rep.",
        "code": "140",
        "votes": 6289
      },
      {
        "label": "Tschad",
        "code": "148",
        "votes": 6158
      },
      {
        "label": "Komoren",
        "code": "174",
        "votes": 5970,
        "lat": -11.6,
        "lng": 43.3
      },
      {
        "label": "Kongo",
        "code": "178",
        "votes": 5809
      },
      {
        "label": "DR Kongo",
        "code": "180",
        "votes": 5617
      },
      {
        "label": "Dschibuti",
        "code": "262",
        "votes": 5422
      },
      {
        "label": "Äquatorialguinea",
        "code": "226",
        "votes": 5269
      },
      {
        "label": "Eritrea",
        "code": "232",
        "votes": 5114
      },
      {
        "label": "Eswatini",
        "code": "748",
        "votes": 4900
      },
      {
        "label": "Gabun",
        "code": "266",
        "votes": 4744
      },
      {
        "label": "Gambia",
        "code": "270",
        "votes": 4597
      },
      {
        "label": "Guinea",
        "code": "324",
        "votes": 4478
      },
      {
        "label": "Guinea-Bissau",
        "code": "624",
        "votes": 4285
      },
      {
        "label": "Elfenbeinküste",
        "code": "384",
        "votes": 4075
      },
      {
        "label": "Lesotho",
        "code": "426",
        "votes": 3917
      },
      {
        "label": "Liberia",
        "code": "430",
        "votes": 3728
      },
      {
        "label": "Libyen",
        "code": "434",
        "votes": 3591
      },
      {
        "label": "Madagaskar",
        "code": "450",
        "votes": 3458
      },
      {
        "label": "Malawi",
        "code": "454",
        "votes": 3282
      },
      {
        "label": "Mali",
        "code": "466",
        "votes": 3072
      },
      {
        "label": "Mauretanien",
        "code": "478",
        "votes": 2929
      },
      {
        "label": "Mauritius",
        "code": "480",
        "votes": 2743,
        "lat": -20.3,
        "lng": 57.6
      },
      {
        "label": "Mosambik",
        "code": "508",
        "votes": 2604
      },
      {
        "label": "Niger",
        "code": "562",
        "votes": 2390
      },
      {
        "label": "Ruanda",
        "code": "646",
        "votes": 2199
      },
      {
        "label": "São Tomé & P.",
        "code": "678",
        "votes": 2072,
        "lat": 0.3,
        "lng": 6.6
      },
      {
        "label": "Seychellen",
        "code": "690",
        "votes": 1911,
        "lat": -4.6,
        "lng": 55.5
      },
      {
        "label": "Sierra Leone",
        "code": "694",
        "votes": 1695
      },
      {
        "label": "Somalia",
        "code": "706",
        "votes": 1546
      },
      {
        "label": "Südsudan",
        "code": "728",
        "votes": 1342
      },
      {
        "label": "Sudan",
        "code": "729",
        "votes": 1170
      },
      {
        "label": "Togo",
        "code": "768",
        "votes": 1017
      },
      {
        "label": "Uganda",
        "code": "800",
        "votes": 830
      },
      {
        "label": "Sambia",
        "code": "894",
        "votes": 723
      },
      {
        "label": "Simbabwe",
        "code": "716",
        "votes": 529
      }
    ]
  },
  {
    "key": "asia",
    "title": "Asien",
    "isos": [
      "764",
      "392",
      "360",
      "704",
      "356",
      "524",
      "144",
      "458",
      "608",
      "410",
      "156",
      "004",
      "051",
      "031",
      "050",
      "064",
      "096",
      "116",
      "268",
      "364",
      "368",
      "376",
      "400",
      "398",
      "414",
      "417",
      "418",
      "422",
      "496",
      "104",
      "408",
      "512",
      "586",
      "275",
      "634",
      "682",
      "760",
      "158",
      "762",
      "626",
      "792",
      "795",
      "784",
      "860",
      "887"
    ],
    "options": [
      {
        "label": "Thailand",
        "code": "764",
        "votes": 8470
      },
      {
        "label": "Japan",
        "code": "392",
        "votes": 8382
      },
      {
        "label": "Indonesien",
        "code": "360",
        "votes": 8135
      },
      {
        "label": "Vietnam",
        "code": "704",
        "votes": 8010
      },
      {
        "label": "Indien",
        "code": "356",
        "votes": 7823
      },
      {
        "label": "Nepal",
        "code": "524",
        "votes": 7660
      },
      {
        "label": "Sri Lanka",
        "code": "144",
        "votes": 7506
      },
      {
        "label": "Malediven",
        "code": "462",
        "votes": 7294,
        "lat": 3.2,
        "lng": 73.2
      },
      {
        "label": "Malaysia",
        "code": "458",
        "votes": 7139
      },
      {
        "label": "Philippinen",
        "code": "608",
        "votes": 6988
      },
      {
        "label": "Singapur",
        "code": "702",
        "votes": 6857,
        "lat": 1.35,
        "lng": 103.8
      },
      {
        "label": "Südkorea",
        "code": "410",
        "votes": 6673
      },
      {
        "label": "China",
        "code": "156",
        "votes": 6446
      },
      {
        "label": "Afghanistan",
        "code": "004",
        "votes": 6349
      },
      {
        "label": "Armenien",
        "code": "051",
        "votes": 6163
      },
      {
        "label": "Aserbaidschan",
        "code": "031",
        "votes": 5959
      },
      {
        "label": "Bahrain",
        "code": "048",
        "votes": 5833,
        "lat": 26,
        "lng": 50.5
      },
      {
        "label": "Bangladesch",
        "code": "050",
        "votes": 5619
      },
      {
        "label": "Bhutan",
        "code": "064",
        "votes": 5467
      },
      {
        "label": "Brunei",
        "code": "096",
        "votes": 5269
      },
      {
        "label": "Kambodscha",
        "code": "116",
        "votes": 5138
      },
      {
        "label": "Georgien",
        "code": "268",
        "votes": 4950
      },
      {
        "label": "Iran",
        "code": "364",
        "votes": 4789
      },
      {
        "label": "Irak",
        "code": "368",
        "votes": 4597
      },
      {
        "label": "Israel",
        "code": "376",
        "votes": 4402
      },
      {
        "label": "Jordanien",
        "code": "400",
        "votes": 4249
      },
      {
        "label": "Kasachstan",
        "code": "398",
        "votes": 4094
      },
      {
        "label": "Kuwait",
        "code": "414",
        "votes": 3880
      },
      {
        "label": "Kirgisistan",
        "code": "417",
        "votes": 3724
      },
      {
        "label": "Laos",
        "code": "418",
        "votes": 3577
      },
      {
        "label": "Libanon",
        "code": "422",
        "votes": 3458
      },
      {
        "label": "Mongolei",
        "code": "496",
        "votes": 3265
      },
      {
        "label": "Myanmar",
        "code": "104",
        "votes": 3055
      },
      {
        "label": "Nordkorea",
        "code": "408",
        "votes": 2897
      },
      {
        "label": "Oman",
        "code": "512",
        "votes": 2708
      },
      {
        "label": "Pakistan",
        "code": "586",
        "votes": 2571
      },
      {
        "label": "Palästina",
        "code": "275",
        "votes": 2438
      },
      {
        "label": "Katar",
        "code": "634",
        "votes": 2262
      },
      {
        "label": "Saudi-Arabien",
        "code": "682",
        "votes": 2052
      },
      {
        "label": "Syrien",
        "code": "760",
        "votes": 1909
      },
      {
        "label": "Taiwan",
        "code": "158",
        "votes": 1723
      },
      {
        "label": "Tadschikistan",
        "code": "762",
        "votes": 1584
      },
      {
        "label": "Timor-Leste",
        "code": "626",
        "votes": 1370
      },
      {
        "label": "Türkei",
        "code": "792",
        "votes": 1179
      },
      {
        "label": "Turkmenistan",
        "code": "795",
        "votes": 1052
      },
      {
        "label": "Ver. Arab. Emirate",
        "code": "784",
        "votes": 891
      },
      {
        "label": "Usbekistan",
        "code": "860",
        "votes": 675
      },
      {
        "label": "Jemen",
        "code": "887",
        "votes": 526
      }
    ]
  },
  {
    "key": "north-america",
    "title": "Nordamerika",
    "isos": [
      "484",
      "840",
      "124",
      "192",
      "188",
      "320",
      "591",
      "214",
      "388",
      "044",
      "084",
      "222",
      "340",
      "558",
      "332",
      "780"
    ],
    "options": [
      {
        "label": "Mexiko",
        "code": "484",
        "votes": 4220
      },
      {
        "label": "USA",
        "code": "840",
        "votes": 4132
      },
      {
        "label": "Kanada",
        "code": "124",
        "votes": 3885
      },
      {
        "label": "Kuba",
        "code": "192",
        "votes": 3760
      },
      {
        "label": "Costa Rica",
        "code": "188",
        "votes": 3573
      },
      {
        "label": "Guatemala",
        "code": "320",
        "votes": 3410
      },
      {
        "label": "Panama",
        "code": "591",
        "votes": 3256
      },
      {
        "label": "Dominik. Rep.",
        "code": "214",
        "votes": 3044
      },
      {
        "label": "Jamaika",
        "code": "388",
        "votes": 2889
      },
      {
        "label": "Bahamas",
        "code": "044",
        "votes": 2738
      },
      {
        "label": "Belize",
        "code": "084",
        "votes": 2607
      },
      {
        "label": "El Salvador",
        "code": "222",
        "votes": 2423
      },
      {
        "label": "Honduras",
        "code": "340",
        "votes": 2196
      },
      {
        "label": "Nicaragua",
        "code": "558",
        "votes": 2099
      },
      {
        "label": "Haiti",
        "code": "332",
        "votes": 1913
      },
      {
        "label": "Trinidad & Tobago",
        "code": "780",
        "votes": 1709
      },
      {
        "label": "Antigua & B.",
        "code": "028",
        "votes": 1583,
        "lat": 17.1,
        "lng": -61.8
      },
      {
        "label": "Barbados",
        "code": "052",
        "votes": 1369,
        "lat": 13.2,
        "lng": -59.5
      },
      {
        "label": "Dominica",
        "code": "212",
        "votes": 1217,
        "lat": 15.4,
        "lng": -61.4
      },
      {
        "label": "Grenada",
        "code": "308",
        "votes": 1019,
        "lat": 12.1,
        "lng": -61.7
      },
      {
        "label": "St. Kitts & N.",
        "code": "659",
        "votes": 888,
        "lat": 17.3,
        "lng": -62.7
      },
      {
        "label": "St. Lucia",
        "code": "662",
        "votes": 700,
        "lat": 13.9,
        "lng": -61
      },
      {
        "label": "St. Vincent",
        "code": "670",
        "votes": 539,
        "lat": 13,
        "lng": -61.2
      }
    ]
  },
  {
    "key": "south-america",
    "title": "Südamerika",
    "isos": [
      "076",
      "032",
      "604",
      "170",
      "152",
      "218",
      "862",
      "068",
      "600",
      "858",
      "328",
      "740"
    ],
    "options": [
      {
        "label": "Brasilien",
        "code": "076",
        "votes": 2350
      },
      {
        "label": "Argentinien",
        "code": "032",
        "votes": 2262
      },
      {
        "label": "Peru",
        "code": "604",
        "votes": 2015
      },
      {
        "label": "Kolumbien",
        "code": "170",
        "votes": 1890
      },
      {
        "label": "Chile",
        "code": "152",
        "votes": 1703
      },
      {
        "label": "Ecuador",
        "code": "218",
        "votes": 1540
      },
      {
        "label": "Venezuela",
        "code": "862",
        "votes": 1386
      },
      {
        "label": "Bolivien",
        "code": "068",
        "votes": 1174
      },
      {
        "label": "Paraguay",
        "code": "600",
        "votes": 1019
      },
      {
        "label": "Uruguay",
        "code": "858",
        "votes": 868
      },
      {
        "label": "Guyana",
        "code": "328",
        "votes": 737
      },
      {
        "label": "Suriname",
        "code": "740",
        "votes": 553
      }
    ]
  },
  {
    "key": "oceania",
    "title": "Ozeanien",
    "isos": [
      "036",
      "554",
      "242",
      "598",
      "090",
      "548"
    ],
    "options": [
      {
        "label": "Australien",
        "code": "036",
        "votes": 2690
      },
      {
        "label": "Neuseeland",
        "code": "554",
        "votes": 2602
      },
      {
        "label": "Fidschi",
        "code": "242",
        "votes": 2355
      },
      {
        "label": "Papua-Neuguinea",
        "code": "598",
        "votes": 2230
      },
      {
        "label": "Salomonen",
        "code": "090",
        "votes": 2043
      },
      {
        "label": "Vanuatu",
        "code": "548",
        "votes": 1880
      },
      {
        "label": "Samoa",
        "code": "882",
        "votes": 1726,
        "lat": -13.8,
        "lng": -172.1
      },
      {
        "label": "Tonga",
        "code": "776",
        "votes": 1514,
        "lat": -21.2,
        "lng": -175.2
      },
      {
        "label": "Kiribati",
        "code": "296",
        "votes": 1359,
        "lat": 1.4,
        "lng": 173
      },
      {
        "label": "Mikronesien",
        "code": "583",
        "votes": 1208,
        "lat": 6.9,
        "lng": 158.2
      },
      {
        "label": "Marshallinseln",
        "code": "584",
        "votes": 1077,
        "lat": 7.1,
        "lng": 171.2
      },
      {
        "label": "Palau",
        "code": "585",
        "votes": 893,
        "lat": 7.5,
        "lng": 134.6
      },
      {
        "label": "Nauru",
        "code": "520",
        "votes": 666,
        "lat": -0.5,
        "lng": 166.9
      },
      {
        "label": "Tuvalu",
        "code": "798",
        "votes": 569,
        "lat": -7.5,
        "lng": 178.7
      }
    ]
  }
];
